[[pages]]
path = "/"
screenshotTimestamp = "2026-03-26T05:53:19Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/qhpRxRC"

[[pages]]
path = "/buscar"
screenshotTimestamp = "2026-03-26T05:52:54Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/5epSPz5"

[[pages]]
path = "/advogado/1"
screenshotTimestamp = "2026-03-25T06:03:47Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/vw4OdsH"

[[pages]]
path = "/categorias"
screenshotTimestamp = "2026-03-25T06:09:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/1dwF2rM"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-03-25T06:10:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/s6b224l"

[[pages]]
path = "/cadastro"
screenshotTimestamp = "2026-03-25T06:10:09Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/WSY9KUs"

[[pages]]
path = "/blog"
screenshotTimestamp = "2026-03-26T05:43:41Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/Gblhac9"

[[pages]]
path = "/advogado/2"
screenshotTimestamp = "2026-03-26T05:43:51Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/itJ1Tn5"

[[pages]]
path = "/buscar?limit=4"
screenshotTimestamp = "2026-03-26T05:44:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/PlP7yhi"

[[pages]]
path = "/precos"
screenshotTimestamp = "2026-03-26T05:52:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/zzn6NDX"

[[pages]]
path = "/calculadora"
screenshotTimestamp = "2026-03-26T05:53:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/U9eRm54"

[[pages]]
path = "/faq"
screenshotTimestamp = "2026-03-26T05:53:09Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/WMlgENA"

[[pages]]
path = "/favoritos"
screenshotTimestamp = "2026-03-26T05:53:21Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/486df6bc-8949-478b-9cd3-1218bb9c64ac/b53515e7-337c-4cbc-a6d0-9e69cdb075be/advNsDe"
